# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire source code and configs
COPY ./src /app/src
COPY ./configs /app/configs
COPY ./weights /app/weights

# Set the default command for running FastAPI or inference
CMD ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
