# Model configuration
model:
  source: "huggingface"        # Options: "huggingface" or "local"
  repo_id: "SerdarHelli/super_res_xray"   # Required if source is "huggingface"
  filename: "net_g.pth" # Model weights filename in HF repo
  weights: "/path/to/weights.pth"  # Optional if using local weights
  scale: 4
  device: "cuda"  # Options: "cuda", "cpu"

# Preprocessing configuration
preprocessing:
  unsharp_mask:
    kernel_size: 7   # Size of the blur kernel
    strength: 2      # Sharpening strength
  brightness:
    factor: 1.2      # Brightness scale factor (1.0 = original)

# Postprocessing configuration
postprocessing:
  clahe:
    clip_limit: 2       # Limit for contrast enhancement
    tile_grid_size:     # Grid size for CLAHE
      - 16
      - 16
